### ISSUE TITLE
sid: 5000000 - bad reference format

### ISSUE THREAD

**Issue by jasonish** [raw-data/MalSilo#3]
In SID 5000000, and maybe others I see:
```
fast_pattern; metadata: reference:url,malsilo.gitlab.io/feeds/dumps/master-feed.json; classtype:trojan-activity;
```
The `metadata:` before the reference is misplaced and shouldn't be there.

**Comment by raw-data** [comment]
Hi @jasonish, thank you for reporting this and sorry for the very long delay in coming back on this. Issue should be now fixed. 

I will close the ticket, but you can drop a message in here, if something is not yet at the stage where it should be.
