### ISSUE TITLE
false positive result

### ISSUE THREAD

**Issue by ipwhois-io** [raw-data/MalSilo#4]
Hello,

I am the founder of the IP geolocation API service ipwhois

One of our domains:
ipwho.is

Defined as a threat. This is a false positive. Please correct.

Thanks in advance.

**Comment by dnmTX** [comment]
Sure,why not,Mr.....FOUNDER: https://www.joesandbox.com/analysis/662346/0/html
👎

**Comment by ipwhois-io** [comment]
> Sure,why not,Mr.....FOUNDER: https://www.joesandbox.com/analysis/662346/0/html 👎

This issue has been fixed for a long time. 
https://www.joesandbox.com/analysis/679216/0/html

**Comment by raw-data** [comment]
@ipwhois-io thank you for the heads-up, entry will be removed in the next 30 minutes. Doing my best to keep an eye on services like the one you are offering, but unfortunately malware authors  use/"abuse" such services quite often, it slipped under the radar.
